common: &common
  adapter: mysql2
  encoding: utf8
  reconnect: false
  pool: 5
  host: localhost

development:
  <<: *common
  database: homebugh_development
  username: root
  password: '123'

test: &test
  <<: *common
  database: homebugh_test
  username: root
  password: '123'

production:
  <<: *common
  database: homebugh_development
  username: root
  password: '123'

cucumber:
  <<: *test
